package IAmNotJustJess.destroyTheMonument.classes.skills;

public enum EffectType {
    DAMAGE_INCREASE_FLAT,
    DAMAGE_INCREASE_MULTIPLIER,
    DAMAGE_DEALT_FLAT,
    DAMAGE_DEALT_PERCENTAGE,
    DAMAGE_VULNERABILITY_FLAT,
    DAMAGE_VULNERABILITY_MULTIPLIER,
    DAMAGE_OVER_TIME,
    POTION_EFFECT,
    HEAL_FLAT,
    HEAL_PERCENTAGE,
    HEAL_OVER_TIME,
    PUSH_AWAY,
    PUSH_UP
}
