package IAmNotJustJess.destroyTheMonument.player.classes.upgrades;

public enum UpgradeAffection {
    MAX_HP,
    MOVEMENT_SPEED,
    MAIN_WEAPON_DAMAGE,
    MAIN_WEAPON_COOLDOWN,
    MAIN_WEAPON_EFFECT,
    SECONDARY_WEAPON_DAMAGE,
    SECONDARY_WEAPON_COOLDOWN,
    SECONDARY_WEAPON_EFFECT,
    ACTIVE_STRENGTH,
    ACTIVE_LONGEVITY,
    ACTIVE_COOLDOWN,
    ACTIVE_EFFECT,
    PASSIVE_STRENGTH,
    PASSIVE_LONGEVITY,
    PASSIVE_COOLDOWN,
    PASSIVE_EFFECT,
    ULTIMATE_STRENGTH,
    ULTIMATE_LONGEVITY,
    ULTIMATE_COOLDOWN,
    ULTIMATE_EFFECT
}
