# Do not change if you do not know what you are doing!
file-version: 1

# Fail colour 1 normal: <#cc2b2b>
# Fail colour 2 lighter: <#e65555>
# Fail colour 3 darker: <#6e1818>

# Success colour 1 normal: <#14db4c>
# Success colour 2 lighter: <#6de38e>
# Success colour 3 darker: <#175e2b>

# Warn colour 1 normal: <#dbd814>
# Warn colour 2 lighter: <#d9d775>
# Warn colour 3 darker: <#5c5b14>

# Shards colour 1 normal: <#19a0e3>
# Shards colour 2 lighter: <#80bbd9>
# Shards colour 3 darker: <#1a5775>